version: '3'

services:
  factorio:
    image: justedro/factorio
    container_name: factorio
    restart: unless-stopped
    ports:
      - "27015:27015"
      - "34197:34197/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/factorio
    environment:
      - TZ=UTC
